{% set name = "oslash" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8090331973ccab85a5266bdb125d3547d0e1d27b0990bd3bc2de2e56bef4a8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - oslash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbrattli/oslash
  summary: Functors, Applicatives, And Monads in Python
  license: MIT
  # PR'd upstread to bundle in license
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
