{% set name = "oslash" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/OSlash-{{ version }}.tar.gz
  sha256: 868aeb58a656f2ed3b73d9dd6abe387b20b74fc9413d3e8653b615b15bf728f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - oslash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbrattli/oslash
  summary: Functors, Applicatives, And Monads in Python 
  license: MIT
  # PR'd upstread to bundle in license
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
